name: 'Curriculum Branch Sync'
author: 'Alex Griffith'
description: 'Automatically creates & pushes master and solution content after the curriculum branch notebook is updated'
runs:
  using: docker
  image: Dockerfile
